spring.application.name=Madhavserver


server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/prepaidrecharge
spring.datasource.username=root
spring.datasource.password=madhav123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Twilio Configuration
twilio.account.sid=AC296854a52d0318f6aa3f16d49513049c
twilio.auth.token=30a6eb3c11ad2278ca444c4fe326139d
twilio.phone.number=+19205008225

cashfree.appId=TEST10533125d7945449f4435ddcae2a52133501
cashfree.secretKey=cfsk_ma_test_c5b3152379da344e4300cf33f1e21bd0_3fa12c97
cashfree.apiUrl=https://sandbox.cashfree.com/pg